# -*- coding: utf-8 -*-
"""Passenger_journey.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/163TmZmytOxQP-9gjyVj87jARf17qwHeY
"""

#  IMPORTING LIBRARIES

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import timedelta

plt.style.use("seaborn-v0_8-darkgrid")   # to make the graph to look cleaner and readable
plt.rcParams["figure.figsize"] = (12,6)  # plots the clearer visualization of the plots

# COVERTING THE EXCEL TO CSV FILE AND LOADING THE DATASET

excel_file = "/content/Daily_Public_Transport_Passenger_Journeys_by_Service_Type_20250603.xlsx"
csv_file = "/content/transport_dataset.csv"

excel_df = pd.read_excel(excel_file)
excel_df.to_csv(csv_file, index=False)

df = pd.read_csv(csv_file)

print("Excel file converted to CSV and loaded successfully.\n")
display(df.head())

# DETECTING DATE AND COLUMN

date_col = None
for col in df.columns:
    if "date" in col.lower():
        date_col = col
        break

if not date_col:
    raise ValueError("No date column found! Please check dataset.")

df[date_col] = pd.to_datetime(df[date_col], errors="coerce")
df = df.dropna(subset=[date_col]).sort_values(date_col)

# DETECTING NUMERIC VALUES AND CLEAN THEM

num_cols = df.select_dtypes(include="number").columns

df[num_cols] = df[num_cols].fillna(method="ffill").fillna(method="bfill")  # CLEANING THE MISSING VALUES

# FEATURE ENGINEERING

for col in num_cols:
    df[col + "_DailyGrowth"] = df[col].pct_change().fillna(0) # ADD DAILY GROWTH FOR EACH NUMERIC FEATURE

df["Traffic_Index"] = df[num_cols].sum(axis=1) # COMBINED TRAFFIC INDEX

# MULTI-LINE TREND OF ALL NUMERIC FEATURES

plt.figure(figsize=(14,7))
for col in num_cols:
    plt.plot(df[date_col], df[col], linewidth=2, label=col)

plt.title("Passenger Trends Across Transport Services", fontsize=16, weight="bold")
plt.xlabel("Date")
plt.ylabel("Passenger Count")
plt.legend()
plt.show()

# HEATMAP OF THE DAILY GROWTH

plt.figure(figsize=(10,6))
growth_cols = [c for c in df.columns if "DailyGrowth" in c]
sns.heatmap(df[growth_cols].corr(), annot=True, cmap="crest")

plt.title("Correlation Between Daily Growth Rates", fontsize=14, weight="bold")
plt.show()

# TRAFFIC INDEX OVER TIME

plt.figure(figsize=(13,6))
plt.plot(df[date_col], df["Traffic_Index"], linewidth=3)

plt.title("Overall Public Transport Traffic Index Over Time", fontsize=16, weight="bold")
plt.xlabel("Date")
plt.ylabel("Traffic Index")
plt.show()

# DISTRIBUTION OF EACH SERVICE TYPE

plt.figure(figsize=(14,7))
for col in num_cols:
    sns.kdeplot(df[col], linewidth=2, label=col)

plt.title("Distribution of Passenger Counts Across Services", fontsize=16, weight="bold")
plt.xlabel("Passenger Count")
plt.legend()
plt.show()